# Copyright 2024 Bytedance Ltd. and/or its affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Reading the scores out of pprint's wrapped repr.

Three shell extractions got this wrong in three different ways: a per-line grep
that matched a key to an empty value, a fixed -A window that cut the dict short,
and an awk range that closed on the wrong line. Each time a key went silently
missing, which reads as "this run did not score it" -- and twice that was one
step from concluding that a run had evaluated different episodes.

So the fixtures here are generated by pprint itself, from dicts chosen so the
break lands between a key and its value, and one asserts that it really does.
"""

import contextlib
import io
import sys
from pathlib import Path
from pprint import pprint

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "scripts"))

import val_scores  # noqa: E402

RAY = "(SFTMultiTaskTaskRunner pid=264168) "


def _pprinted(metrics):
    buf = io.StringIO()
    with contextlib.redirect_stdout(buf):
        pprint(f"Initial validation metrics: {metrics}")
    return buf.getvalue().splitlines()


def _log(path, metrics, *, repeats=1, prefix=RAY, noise=True):
    lines = ["some earlier output"] if noise else []
    for _ in range(repeats):
        lines += [prefix + line for line in _pprinted(metrics)]
        if noise:
            lines.append(prefix + "more output between blocks")
    path.write_text("\n".join(lines) + "\n")
    return path


BASE = {
    "val/alfworld/test_score": 3.886072174172383,
    "val/webshop/test_score": 6.064382139148495,
    "val/search/test_score": 0.3586502562804531,
    "val/alfworld_pick_cool_then_place_in_recep_success_rate": 0.5,
    "val/search_success_rate": 0.3856441357338809,
    "val/success_rate": 0.4012345678901234,
}


def test_the_fixture_really_does_split_a_key_from_its_value():
    """A regression test for line wrapping must contain line wrapping."""
    for padding in range(0, 40):
        metrics = {f"val/pad{i}": 0.1 for i in range(padding)}
        metrics.update(BASE)
        text = "\n".join(_pprinted(metrics))
        if "'val/success_rate': \"\n" in text:
            return
    pytest.fail("no padding produced a break between a key and its value")


def _split_metrics():
    for padding in range(0, 40):
        metrics = {f"val/pad{i}": 0.1 for i in range(padding)}
        metrics.update(BASE)
        if "'val/success_rate': \"\n" in "\n".join(_pprinted(metrics)):
            return metrics
    raise AssertionError("no split found")


def test_a_value_on_the_line_after_its_key_is_still_read(tmp_path):
    metrics = _split_metrics()
    got = val_scores.scores(str(_log(tmp_path / "a.log", metrics)))
    assert got["val/success_rate"] == pytest.approx(0.4012345678901234)
    assert len(got) == len(metrics)


def test_every_key_survives_however_long_the_dict(tmp_path):
    """A fixed -A window dropped the tail of the dict, and val/success_rate with it."""
    metrics = {f"val/task{i}/test_score": i / 100 for i in range(60)}
    metrics.update(BASE)
    got = val_scores.scores(str(_log(tmp_path / "long.log", metrics)))
    assert set(got) == set(metrics)
    assert got["val/alfworld_pick_cool_then_place_in_recep_success_rate"] == 0.5


def test_the_last_block_wins_when_a_log_holds_two(tmp_path):
    """Real logs print the metrics more than once."""
    first = dict(BASE, **{"val/success_rate": 0.1})
    path = tmp_path / "two.log"
    lines = [RAY + l for l in _pprinted(first)] + ["middle"] + \
            [RAY + l for l in _pprinted(dict(BASE, **{"val/success_rate": 0.9}))]
    path.write_text("\n".join(lines) + "\n")
    assert val_scores.scores(str(path))["val/success_rate"] == pytest.approx(0.9)


def test_a_log_with_no_metrics_is_empty_rather_than_wrong(tmp_path):
    path = tmp_path / "none.log"
    path.write_text("nothing here\n(pid=1) [val-pipeline] final: 139 batches over 3016.0s\n")
    assert val_scores.scores(str(path)) == {}


def test_the_ray_prefix_is_stripped(tmp_path):
    plain = val_scores.scores(str(_log(tmp_path / "plain.log", BASE, prefix="")))
    prefixed = val_scores.scores(str(_log(tmp_path / "pref.log", BASE)))
    assert plain == prefixed == {k: pytest.approx(v) for k, v in BASE.items()}


def test_a_diff_names_metrics_only_one_run_scored(tmp_path, capsys):
    """Two runs that scored different things is a finding, not a rounding."""
    a = _log(tmp_path / "a.log", BASE)
    dropped = {k: v for k, v in BASE.items() if "pick_cool" not in k}
    b = _log(tmp_path / "b.log", dropped)
    val_scores.main([str(a), str(b)])
    out = capsys.readouterr().out
    assert "ONLY IN ONE" in out
    assert "pick_cool" in out
    assert "1 metric(s) in only one run" in out


def test_a_diff_of_identical_runs_says_so(tmp_path, capsys):
    a = _log(tmp_path / "a.log", BASE)
    b = _log(tmp_path / "b.log", BASE)
    val_scores.main([str(a), str(b)])
    out = capsys.readouterr().out
    assert "both runs scored the same" in out
    assert "ONLY IN ONE" not in out


def test_a_line_from_another_actor_between_two_fragments_is_not_the_end(tmp_path):
    """Ray forwards several actors into one stream.

    The first version of this reader treated "not a fragment" as the end of the
    block, so it stopped at the first interleaved line and reported nothing --
    on a real log, while passing on a synthetic one that had nothing to
    interleave.
    """
    metrics = _split_metrics()
    fragments = _pprinted(metrics)
    lines = []
    for index, fragment in enumerate(fragments):
        lines.append(RAY + fragment)
        if index == 1:
            lines.append("(WorkerDict pid=99) [rollout-pump] round 4123 done")
    path = tmp_path / "interleaved.log"
    path.write_text("\n".join(lines) + "\n")
    got = val_scores.scores(str(path))
    assert set(got) == set(metrics)
    assert got["val/success_rate"] == pytest.approx(0.4012345678901234)


def test_metrics_printed_without_pprint_quoting_are_still_read(tmp_path):
    """A shape neither pprint version here produces, read by the salvage path.

    The failure this guards is not "the format changed" but what it looks like
    when it does: an empty table, which is exactly what a run that scored
    nothing produces.
    """
    path = tmp_path / "plain.log"
    path.write_text(
        "noise\n"
        + RAY + "Initial validation metrics: {'val/success_rate': 0.4, 'val/search/test_score': 0.35}\n"
        + RAY + "more output\n"
    )
    got = val_scores.scores(str(path))
    assert got == {"val/success_rate": pytest.approx(0.4),
                   "val/search/test_score": pytest.approx(0.35)}


def test_the_salvage_path_does_not_join_unrelated_parts_of_a_long_log(tmp_path):
    """Bounded, so it cannot invent a pair out of two distant lines."""
    path = tmp_path / "far.log"
    lines = [RAY + "Initial validation metrics: {'val/success_rate': "]
    lines += [RAY + f"unrelated {i}" for i in range(600)]
    lines += [RAY + "0.9}"]
    path.write_text("\n".join(lines) + "\n")
    assert "val/success_rate" not in val_scores.scores(str(path))


def test_an_unreadable_log_says_what_it_saw(tmp_path, capsys):
    """An empty table from a broken reader and from a run that did not score
    look identical; this makes the difference visible in one step."""
    path = tmp_path / "weird.log"
    path.write_text("noise\n" + RAY + "Initial validation metrics: <repr suppressed>\n")
    val_scores.main([str(path)])
    out = capsys.readouterr().out
    assert "NO validation metrics found" in out
    assert "as this reader sees it" in out
    assert "not a fragment" in out


def test_an_incomplete_block_is_completed_rather_than_believed(tmp_path):
    """The salvage ran only when the block reader found NOTHING.

    So a block reader that returned something INCOMPLETE was never corrected,
    and the missing keys came out as "only in one run" -- the exact false
    signal this script exists to prevent. It produced one: val/success_rate
    reported as scored by one run and not the other, on two runs that scored
    both.
    """
    metrics = _split_metrics()
    fragments = _pprinted(metrics)
    assert len(fragments) >= 4, fragments

    # One fragment carries a prefix shape the reader does not recognise, so the
    # block reader skips that line and assembles the block WITHOUT it. Nothing
    # is removed from the file: the keys are still there to be found.
    lines = []
    for index, fragment in enumerate(fragments):
        # A timestamp rather than Ray's parenthesised prefix: not stripped, so
        # the line does not look like a fragment and the block reader skips it.
        prefix = "2026-08-28 15:57:01 " if index == 1 else RAY
        lines.append(prefix + fragment)
    path = tmp_path / "truncated.log"
    path.write_text("\n".join(lines) + "\n")

    # The block reader alone loses whatever was on that line.
    from_blocks = {}
    with open(path) as handle:
        for block in val_scores._joined_blocks(handle.read()):
            for key, value in val_scores._PAIR.findall(block):
                from_blocks[key] = float(value)
    assert set(from_blocks) != set(metrics), "the fixture no longer breaks the block reader"

    got = val_scores.scores(str(path))
    assert set(got) == set(metrics), sorted(set(metrics) - set(got))


def test_a_missing_value_is_not_printed_as_a_negative_number(tmp_path, capsys):
    a = _log(tmp_path / "a.log", BASE)
    b = _log(tmp_path / "b.log", {k: v for k, v in BASE.items() if k != "val/success_rate"})
    val_scores.main([str(a), str(b)])
    line = next(l for l in capsys.readouterr().out.splitlines()
                if l.startswith("val/success_rate"))
    assert "ONLY IN ONE" in line
    assert "-0." not in line, line
